[tool.poetry]
name = "network-devices"
version = "0.1.0"
description = "Get connected network devices from fritz.box"
license = "MIT"
authors = ["Ralf Vogler <ralf.vogler@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
fritzconnection = "^1.8.0"
